doctrine_migrations:
    migrations_paths:
        'DoctrineMigrations': '%kernel.project_dir%/src/Infrastructure/Shared/Migrations'
    organize_migrations: false
    enable_profiler: '%kernel.debug%'
