parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'
        exclude:
            - '../src/Domain/'
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'
            - '../src/Infrastructure/Shared/Migrations'

    # Configuration spécifique pour les contrôleurs
    App\Infrastructure\Web\Controller\:
        resource: '../src/Infrastructure/Web/Controller'
        tags: ['controller.service_arguments']

